### ISSUE TITLE
error with Installation

### ISSUE THREAD

**Issue by allrude** [powerbuoy/sleek#11]
Hi this looks promising so i did an install, but got ```unable to locate 'src/assets/' at '/Users/xxxxx/projects/wordpress/sleek/wp-content/themes/sleek/src/assets/**/*'```

guess something is missing ;-)

**Comment by powerbuoy** [comment]
When you say install do you mean npm install? Composer install? Or something else? What command did you run when you encountered the error?

**Comment by liamb13** [comment]
You need to run `npm run fontello` as it creates an assets folder in src.
