### ISSUE TITLE
Getting this when i run 'npm run build' I am on PC and Windows 10

### ISSUE THREAD

**Issue by Mangemannen66** [powerbuoy/sleek#6]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v13.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Sleek@1.0.0~prebuild: Sleek@1.0.0
6 info lifecycle Sleek@1.0.0~build: Sleek@1.0.0
7 verbose lifecycle Sleek@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle Sleek@1.0.0~build: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\wamp64\www\duade\wp-content\themes\sleek\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;D:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\wamp64\bin\php\php7.3.5;C:\ProgramData\ComposerSetup\bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;D:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\wamp64\bin\php\php7.3.5;C:\ProgramData\ComposerSetup\bin;C:\Users\Magnus Daneling\AppData\Local\Microsoft\WindowsApps;C:\Users\Magnus Daneling\AppData\Roaming\npm;C:\wamp64\bin\php;C:\Program Files\heroku\bin;C:\Users\Magnus Daneling\AppData\Roaming\Composer\vendor\bin;;c:\wp-cli
9 verbose lifecycle Sleek@1.0.0~build: CWD: C:\wamp64\www\duade\wp-content\themes\sleek
10 silly lifecycle Sleek@1.0.0~build: Args: [ '/d /s /c', 'webpack --mode production' ]
11 silly lifecycle Sleek@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle Sleek@1.0.0~build: Failed to exec build script
13 verbose stack Error: Sleek@1.0.0 build: `webpack --mode production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid Sleek@1.0.0
15 verbose cwd C:\wamp64\www\duade\wp-content\themes\sleek
16 verbose Windows_NT 10.0.18363
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v13.1.0
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 2
22 error Sleek@1.0.0 build: `webpack --mode production`
22 error Exit status 2
23 error Failed at the Sleek@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by Mangemannen66** [comment]
Solved it by uncomment @import "icons"; and then: npm run build. Afterwoths I did npm run fontello and then open up @import "icons"; again and then npm run dev to start working =)

**Comment by powerbuoy** [comment]
Oh right, yes you need to run `npm run fontello` before `npm run dev` because `app.scss` is trying to import `icons.scss` which are generated by `npm run fontello`
