### ISSUE TITLE
How use smooth loader

### ISSUE THREAD

**Issue by jsonpreet** [powerbuoy/sleek#8]
how i can use smoother page loader, i mean when click on any link it change page url with smooth effect on your demo, on my demo is show as normal page reload

**Comment by powerbuoy** [comment]
That's not something that comes with Sleek but something I built specifically for the Sleek website. You can check the needed CSS/JS here: 

https://github.com/powerbuoy/sleek/blob/web/functions.php#L184
https://github.com/powerbuoy/sleek/blob/web/src/js/page-transition.js
https://github.com/powerbuoy/sleek/blob/web/src/sass/webstyle/modules/page-transition.scss
